# -*- coding: utf-8 -*-
"""Projet_RCP_217.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ggtPTuUinCN21tNiEjV_g1dULxrQ2jcT

**Installation des libraries: A executer sur Colab** : Création d'un fichier requirements contenant la liste des libraire puis execution de ce fichier.
"""

requirements_content = """
ultralytics
deep-sort-realtime
motmetrics
opencv-python
numpy
tensorrt-cu12
onnxruntime-gpu
onnx>=1.12.0
onnxslim>=0.1.71
"""

with open("requirements.txt", "w") as f:
    f.write(requirements_content)

# Installation silencieuse
print("Installation des librairies en cours...")
!pip install -r requirements.txt -q
print("Installation terminée")

"""**Montage du Drive:  A executer sur google Colab**"""

from google.colab import drive
drive.mount('/content/drive')

"""**Copie et Dézip:A executer sur google Colab**"""

# On copie le fichier vers l'espace local ultra-rapide de Colab
!cp "/content/drive/MyDrive/Colab Notebooks/MOT20.zip" /content/MOT20.zip #Modifier le chemin selon où est localisé MOT20 dans le Drive

# On dézippe (cela peut prendre 1 à 2 minutes pour 5 Go)
!unzip -q /content/MOT20.zip -d /content/datasets

"""**Création du fichier** .YAML : Le fichier .yaml est nécessaire à ultralytics pour configurer les chemins et les classes à détecter"""

yaml_content = """
train:
  - /content/datasets/MOT20/train/MOT20-02/images
  - /content/datasets/MOT20/train/MOT20-03/images
  - /content/datasets/MOT20/train/MOT20-05/images

val:
  - /content/datasets/MOT20/train/MOT20-01/images

nc: 1
names:
  0: person
"""

with open("data.yaml", "w") as f:
    f.write(yaml_content)

"""**Chemins d'entrée et de sortie**"""

# chemin local sur le serveur Colab
Chemin_Train = "/content/datasets/MOT20/train"
Chemin_Test = "/content/datasets/MOT20/test"
# Dossier de sortie
Dossierbaseline_out = "/content/outputs_baseline"
Dossierfinetuning_out= "/content/outputs_finetuning"
Dossier_out="/content/to_send"

"""**Imports**"""

import os
import time
import cv2
import numpy as np
from ultralytics import YOLO
from deep_sort_realtime.deepsort_tracker import DeepSort
import motmetrics as mm
from google.colab.patches import cv2_imshow
import shutil
import configparser
import torch
import ultralytics
import configparser
import shutil
import gc

"""**Configuration**"""

# ----------------- CONFIGURATION -------------------------------------------------#
Seuil_Confiance = 0.5 # YOLO ne transmet pas à DeepSort les détections avec un seuil de confiance inférieur à Seuil_Confiance
# OPTIONS D'AFFICHAGE
Afficher_vid = False  # Mettre à True pour afficher la video et False pour un traitement plus rapide
Resize = (1280, 720)  # Redimensionner l'affichage uniquement (ou None)
Log = 50  # afficher une ligne complète toutes les Log trames (0 = toutes)

if not hasattr(np, 'asfarray'):
    np.asfarray = lambda x, **kwargs: np.asarray(x, dtype=float, **kwargs) # Correction pour numpy > v2

"""**Création du dossier de sortie et lister les séquences**"""

os.makedirs(Dossierbaseline_out, exist_ok=True) # Créer le dossier de sortie
os.makedirs(Dossierfinetuning_out, exist_ok=True) # Créer le dossier de sortie
model = YOLO("yolov8n.pt") # Choix du modèle yolo
model.export(format="engine", device=0, imgsz=640,half=True, simplify=True)
model = YOLO("yolov8n.engine")
# Lister toutes les séquences (sous-dossiers)
sequences_train = [d for d in os.listdir(Chemin_Train) if os.path.isdir(os.path.join(Chemin_Train, d))]
sequences_test = [d for d in os.listdir(Chemin_Test) if os.path.isdir(os.path.join(Chemin_Test, d))]

"""**Mise en forme des labels à partir de "gt.txt" pour le Fine Tuning** : Yolo a besoin d'un fichier par image."gt.txt" doit alors être parsé pour construire un fichiers de labels pour pouvoir effectuer l'entraînement"""

def get_sequence_info(seq_path):
    """Lit le fichier seqinfo.ini pour obtenir la résolution et le dossier des images."""
    ini_path = os.path.join(seq_path, 'seqinfo.ini')
    if not os.path.exists(ini_path):
        raise FileNotFoundError(f"seqinfo.ini manquant dans {seq_path}")

    config = configparser.ConfigParser()
    config.read(ini_path)

    w = int(config.get('Sequence', 'imWidth'))
    h = int(config.get('Sequence', 'imHeight'))
    img_dir = config.get('Sequence', 'imDir')
    return w, h, img_dir

def process_mot_in_place(mot_root):
    """
    Convertit les labels MOT en YOLO et réorganise les dossiers
    pour la compatibilité Ultralytics.
    """
    # 1. Lister les séquences (MOT20-01, MOT20-02, etc.)
    sequences = [d for d in os.listdir(mot_root) if os.path.isdir(os.path.join(mot_root, d))]

    for seq in sequences:
        seq_path = os.path.join(mot_root, seq)
        print(f"--- Traitement de {seq} ---")

        # 2. Renommer 'img1' en 'images' (CRUCIAL pour YOLO)
        old_img_path = os.path.join(seq_path, 'img1')
        new_img_path = os.path.join(seq_path, 'images')

        if os.path.exists(old_img_path):
            # Supprimer le dossier 'images' s'il existe déjà pour éviter les erreurs de renommage
            if os.path.exists(new_img_path):
                shutil.rmtree(new_img_path)
            os.rename(old_img_path, new_img_path)
            print(f"Renommé : img1 -> images")

        # Récupérer les infos de résolution
        try:
            w, h, _ = get_sequence_info(seq_path)
        except Exception as e:
            print(f"Erreur seqinfo pour {seq}: {e}")
            continue

        # Préparer le dossier labels (au même niveau que 'images')
        labels_out = os.path.join(seq_path, 'labels')
        if os.path.exists(labels_out):
            shutil.rmtree(labels_out)
        os.makedirs(labels_out, exist_ok=True)

        gt_file = os.path.join(seq_path, 'gt', 'gt.txt')
        if not os.path.exists(gt_file):
            print(f"Pas de fichier gt.txt trouvé pour {seq}")
            continue

        # Conversion du fichier gt.txt
        count = 0
        with open(gt_file, 'r') as f:
            for line in f:
                parts = line.strip().split(',')
                if len(parts) < 7: continue

                # Filtrer Pedestrian (Classe 1 dans MOT20)
                if parts[7] != '1': continue

                frame_id = int(parts[0])
                xmin, ymin, width, height = float(parts[2]), float(parts[3]), float(parts[4]), float(parts[5])

                # Calcul YOLO (Normalisé 0-1)
                x_center = (xmin + width / 2.0) / w
                y_center = (ymin + height / 2.0) / h
                w_norm = width / w
                h_norm = height / h

                label_filename = f"{frame_id:06d}.txt"
                label_path = os.path.join(labels_out, label_filename)

                with open(label_path, 'a') as lf:
                    lf.write(f"0 {x_center:.6f} {y_center:.6f} {w_norm:.6f} {h_norm:.6f}\n")
                count += 1

        #  Supprimer les anciens fichiers cache pour forcer un nouveau scan
        cache_file = os.path.join(seq_path, "images.cache")
        if os.path.exists(cache_file):
            os.remove(cache_file)

        print(f"Terminé : {count} annotations créées.")

# EXECUTION
train_path = '/content/datasets/MOT20/train'
test_path = '/content/datasets/MOT20/test'
process_mot_in_place(train_path)
process_mot_in_place(test_path)
print("\n Structure prête pour YOLO.")

"""**Fonction qui permet de générer les résultats sous format MOT après avoir combiné les deux briques YOLO et DeepSort**"""

def genererMOT(model, Chemin, Dossierbaseline_out, sequences, Seuil_Confiance, Afficher_vid, Resize, Log):
    if os.path.exists(Dossierbaseline_out):
        print(f"[INFO] Suppression de l'ancien dossier : {Dossierbaseline_out}")
        shutil.rmtree(Dossierbaseline_out)

    os.makedirs(Dossierbaseline_out, exist_ok=True)
    try:
        for seq in sequences:
            print(f"\n--- Traitement de la séquence : {seq} ---")

            seq_path = os.path.join(Chemin, seq, "images")
            save_dir = os.path.join(Dossierbaseline_out, seq)
            os.makedirs(save_dir, exist_ok=True)

            # Utilisation de 'with' pour garantir la fermeture des fichiers
            det_path = os.path.join(save_dir, "det.txt")
            track_path = os.path.join(save_dir, f"{seq}.txt")

            with open(det_path, "w") as det_file, open(track_path, "w") as track_file:

                tracker = DeepSort(max_age=30, n_init=3, nms_max_overlap=1.0, max_cosine_distance=0.2)
                image_files = sorted([f for f in os.listdir(seq_path) if f.lower().endswith(('.jpg', '.png'))])
                total_frames = len(image_files)

                if total_frames == 0:
                    print(f"[WARN] Aucune image trouvée dans {seq_path}, skip.")
                    continue

                frame_idx = 1
                t_start = time.time()

                for img_name in image_files:
                    img_path = os.path.join(seq_path, img_name)
                    frame = cv2.imread(img_path)
                    if frame is None:
                        frame_idx += 1
                        continue

                    if Log == 0:
                        print(f"Sequence {seq} — frame {frame_idx}/{total_frames}", end='\r', flush=True)
                    elif frame_idx % Log == 0 or frame_idx == 1 or frame_idx == total_frames:
                        print(f"Sequence {seq} — frame {frame_idx}/{total_frames}")

                    results = model(frame, verbose=False)
                    yolo_dets = []

                    for r in results:
                        for box in r.boxes:
                            cls_id = int(box.cls.cpu().numpy()[0])
                            if cls_id != 0: continue

                            x1, y1, x2, y2 = box.xyxy.cpu().numpy()[0]
                            conf = float(box.conf.cpu().numpy()[0])

                            if conf >= Seuil_Confiance:
                                w, h = x2 - x1, y2 - y1
                                yolo_dets.append([[x1, y1, w, h], conf, "person"])
                                det_file.write(f"{frame_idx},-1,{x1:.2f},{y1:.2f},{w:.2f},{h:.2f},{conf:.3f},-1,-1,-1\n")

                    tracks = tracker.update_tracks(yolo_dets, frame=frame)

                    for track in tracks:
                        if not track.is_confirmed(): continue

                        tid = track.track_id
                        l, t, rgt, b = track.to_ltrb()
                        tw, th = rgt - l, b - t
                        track_file.write(f"{frame_idx},{tid},{l:.2f},{t:.2f},{tw:.2f},{th:.2f},1,-1,-1,-1\n")

                        if Afficher_vid:
                            cv2.rectangle(frame, (int(l), int(t)), (int(rgt), int(b)), (0, 255, 0), 2)
                            cv2.putText(frame, f"ID:{tid}", (int(l), int(t)-5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,0), 2)

                    if Afficher_vid:
                        display_frame = cv2.resize(frame, Resize) if Resize else frame
                        cv2.imshow("MOT20 Multi-Sequence Tracker", display_frame)
                        if cv2.waitKey(1) & 0xFF == ord('q'):
                            break

                    frame_idx += 1

                duration = time.time() - t_start
                fps = (frame_idx - 1) / duration if duration > 0 else 0.0
                print(f"\nSéquence {seq} terminée : {frame_idx - 1} trames ({fps:.2f} FPS)")

    except KeyboardInterrupt:
        print("\n[INFO] Interruption clavier détectée.")

    finally:

        if Afficher_vid:
            try:
                cv2.destroyAllWindows()
            except:
                pass
        print("[INFO] Traitement terminé.")

"""**Execution de générer MOT sur les données d'entraînement**"""

genererMOT(model, Chemin_Train, Dossierbaseline_out, sequences_train, Seuil_Confiance, Afficher_vid=False, Resize=Resize, Log=Log)

"""**Fonction qui évalue les performances : mota', 'idf1', 'motp', 'num_switches', 'precision', 'recall'**"""

#---------------------------Performances----------------------------------------------#
def evaluate_mot_results(Chemin,Dossierbaseline_out,sequences):
    accs = []
    names = []

    # Vérification de l'existence du dossier de résultats
    if not os.path.exists(Dossierbaseline_out):
        print(f"Le dossier {Dossierbaseline_out} n'existe pas.")
        return

    sequences = [d for d in os.listdir(Dossierbaseline_out) if os.path.isdir(os.path.join(Dossierbaseline_out, d))]

    for seq in sequences:
        print(f"--- Analyse en cours : {seq} ---")

        gt_file = os.path.join(Chemin, seq, "gt", "gt.txt")
        res_file = os.path.join(Dossierbaseline_out, seq, f"{seq}.txt")

        if not os.path.exists(gt_file) or not os.path.exists(res_file):
            print(f"Fichiers manquants pour {seq}. Vérifiez gt.txt et votre sortie .txt")
            continue

        # Chargement des données
        gt_data = mm.io.loadtxt(gt_file, fmt="mot16")
        res_data = mm.io.loadtxt(res_file, fmt="mot16")

        acc = mm.MOTAccumulator(auto_id=True)

        # Extraction des indices de trames (frames)
        # On utilise .index.get_level_values(0) car motmetrics utilise un MultiIndex (Frame, ID)
        all_frames = gt_data.index.get_level_values(0).unique()

        for frame in all_frames:
            # Données de vérité terrain (GT)
            gt_frame = gt_data.loc[frame]
            gt_ids = gt_frame.index.values
            gt_boxes = gt_frame.iloc[:, 0:4].values

            # Données de vos prédictions (RES)
            if frame in res_data.index.get_level_values(0):
                res_frame = res_data.loc[frame]
                res_ids = res_frame.index.values
                res_boxes = res_frame.iloc[:, 0:4].values
            else:
                # Si aucune détection pour cette trame
                res_ids = []
                res_boxes = np.empty((0, 4))

            # Calcul de la distance IoU
            distances = mm.distances.iou_matrix(gt_boxes, res_boxes, max_iou=0.5)

            # Mise à jour de l'accumulateur (C'est ici que le MOTA se construit)
            acc.update(gt_ids, res_ids, distances)

        accs.append(acc)
        names.append(seq)

    # Synthèse des résultats
    mh = mm.metrics.create()
    summary = mh.compute_many(
        accs,
        metrics=['mota', 'idf1', 'motp', 'num_switches', 'precision', 'recall'],
        names=names,
        generate_overall=True
    )

    print("\n" + "="*80)
    print(" RÉSULTATS DE L'ÉVALUATION MOTA")
    print("="*80)

    print(mm.io.render_summary(summary, formatters=mh.formatters, namemap=mm.io.motchallenge_metric_names))

"""**Execution de l'évaluation de performance sur les données d'entraînement**"""

evaluate_mot_results(Chemin_Train,Dossierbaseline_out,sequences_train)

"""**Fine Tuning : Réentraînement du modèle**"""

#---------------------------Réentraînement-------------------------------#n)
model_Finetuning = YOLO("yolov8n.pt")
#model_Finetuning = YOLO("runs/detect/yolo_mot20/weights/last.pt")
results = model_Finetuning.train(data="data.yaml",epochs=100,imgsz=640,batch=16,name="yolo_mot20",device=0,save=True,resume=False) # Mettre resume à True si c'est une reprise
path_to_best = f"runs/detect/yolo_mot20/weights/best.pt"
model_best = YOLO(path_to_best)

# Exportation en TensorRT (.engine) pour une vitesse maximale
model_best.export(format="engine", device=0, imgsz=640, half=True, simplify=True)

# Charger le modèle optimisé pour l'utiliser (Inférence/Predict)
model_optimized = YOLO("runs/detect/yolo_mot20/weights/best.engine")

"""**Génération sous Format MOT et évaluation du modèle réentraîné**"""

#Générer les fichiers MOT avec le meilleur modèle
# Exportation en TensorRT (.engine) pour une vitesse maximale
model_Finetuning = YOLO("runs/detect/yolo_mot20/weights/best.pt")
#model_Finetuning.export(format="engine", device=0, imgsz=640, half=True, simplify=True)
#model_optimized = YOLO("best.engine")
genererMOT(model_Finetuning,Chemin_Train,Dossierfinetuning_out,sequences_train,Seuil_Confiance,Afficher_vid, Resize ,Log)
# Évaluation finale
print("\n" + "="*40)
print("--- ÉVALUATION DU MODÈLE RÉENTRAÎNÉ (FINE-TUNED) ---")
print("="*40)

evaluate_mot_results(Chemin_Train,Dossierfinetuning_out,sequences_train)

"""Générer MOT pour les données de test à soumettre pour le challenge MOT20"""

#Générer les fichiers MOT avec le MEILLEUR modèle et les données de test
genererMOT(model_optimized,Chemin_Test,Dossier_out,sequences_test,Seuil_Confiance,Afficher_vid, Resize ,Log)